### ISSUE TITLE
Fix UnicodeEncodeError

### ISSUE THREAD

**Issue by raresraf** [raresraf/rafMetrics#1]
```
Browser: Chrome
URL: https://www.emag.ro/
Traceback (most recent call last):
  File "./WebsiteMonitorHelpers/speedprofile.py", line 99, in <module>
    RUN.create_har(args)
  File "./WebsiteMonitorHelpers/speedprofile.py", line 74, in create_har
    self.__store_into_file(args,'har', result)
  File "./WebsiteMonitorHelpers/speedprofile.py", line 31, in __store_into_file
    har_file.write(str(result))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 172706: ordinal not in range(128)
time.struct_time(tm_year=2019, tm_mon=11, tm_mday=9, tm_hour=21, tm_min=21, tm_sec=49, tm_wday=5, tm_yday=313, tm_isdst=0)
30.71
Docker run status: success
Traceback (most recent call last):
  File "WebsiteManager.py", line 108, in <module>
    WebsiteManager(3600).start()
  File "WebsiteManager.py", line 104, in start
    self.run()
  File "WebsiteManager.py", line 18, in run
    monitor_result = monitor.run()
  File "/home/WebMonitoring/WebsiteMonitor.py", line 80, in run
    self.process_json()
  File "/home/WebMonitoring/WebsiteMonitor.py", line 60, in process_json
    data = json.load(json_file)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by raresraf** [comment]
Fixed - https://github.com/raresraf/rafMetrics/commit/76cdb47cf3427c171d5287701c0c12763da9e9ed
